import { colors } from './tokens';

// Opt-in semantic palettes. Legacy colors/communityColors remain fixed light values.
export const lightThemeColors = Object.freeze({
  background: colors.background,
  surface: colors.surface,
  surfaceSecondary: '#F3F4F6',
  cardBackground: colors.background,
  moreButtonBackground: colors.moreButtonBackground,
  skeletonBackground: '#F1F3F5',
  tagBackground: '#F3F4F6',
  tagText: '#4B5563',
  inactiveIcon: colors.inactiveText,
  bannerFallback: '#252525',
  textPrimary: colors.text,
  textSecondary: colors.secondaryText,
  border: colors.border,
  accent: colors.primary,
  onAccent: '#FFFFFF',
  onImage: '#FFFFFF',
  imageShade: '#000000',
  filterUnselectedBg: colors.background,
  filterUnselectedText: colors.text,
  filterSelectedBg: colors.text,
  filterSelectedText: colors.background,
  searchBackground: colors.background,
  bottomSheetBg: colors.background,
  navIndicator: 'rgba(0, 0, 0, 0.09)',
  // FloatingTabBar currently uses black for both icon states.
  navIcon: '#000000',
  navIconInactive: '#000000',
  ongoingBg: colors.primaryLight,
  ongoingText: colors.primaryDark,
  upcomingBg: colors.infoLight,
  upcomingText: colors.infoDark,
  endedBg: '#F3F4F6',
  endedText: colors.secondaryText,
});

export type ThemeColors = { readonly [Key in keyof typeof lightThemeColors]: string };

export const darkThemeColors: ThemeColors = Object.freeze({
  background: '#121212',
  surface: '#242424',
  surfaceSecondary: '#303030',
  cardBackground: '#242424',
  moreButtonBackground: '#242424',
  skeletonBackground: '#303030',
  tagBackground: '#303030',
  tagText: '#B0B0B0',
  inactiveIcon: '#B0B0B0',
  bannerFallback: '#242424',
  textPrimary: '#F5F5F5',
  textSecondary: '#B0B0B0',
  border: '#484848',
  accent: '#22C55E',
  onAccent: '#071B0E',
  onImage: '#FFFFFF',
  imageShade: '#000000',
  filterUnselectedBg: '#303030',
  filterUnselectedText: '#F5F5F5',
  filterSelectedBg: '#22C55E',
  filterSelectedText: '#071B0E',
  searchBackground: '#242424',
  bottomSheetBg: '#242424',
  navIndicator: '#484848',
  navIcon: '#F5F5F5',
  navIconInactive: '#B0B0B0',
  ongoingBg: '#173B27',
  ongoingText: '#4ADE80',
  upcomingBg: '#3B2D15',
  upcomingText: '#FBBF24',
  endedBg: '#303030',
  endedText: '#B0B0B0',
});
